# Title: DM1590 Final Project Template

## Authors: Markus Brewitz, Linus Wallin, Saga Jonasson, Vilhelm Norström, Martin Ryberg Laude

---

### Background and motivation

News articles come in a variety of subjects and categories describing their field and relevance. Some of these have self-reported tags, but too many do not, or provide inaccurate tags. Tagging articles has the potential to help information-seekers to judge the relevance of articles and filter them by interest, especially in this day and age where information is so abundant it can be exhausting. In this project we set out to use machine learning to tag articles based on their titles, to aid the effort of searching for relevant information.

### Dataset

https://archive.ics.uci.edu/ml/datasets/News+Aggregator

This dataset contains tags along with corresponding news titles, which we use to train our models.

### Methodology

Describe what you are doing and how you are doing it.

---

### Import dataset:

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

column_names = ["id", "title", "url", "publisher", "category", "story", "hostname", "timestamp"]
data = pd.read_csv('NewsAggregatorDataset/newsCorpora.csv',sep='\t',header=None, names=column_names)
#print(data)


vect = CountVectorizer()
vect.fit(data["title"])
print("Vocabulary size: {}".format(len(vect.vocabulary_)))
#print("Vocabulary content:\n {}".format(vect.vocabulary_))
bag_of_words = vect.transform(data)
print("bag_of_words: {}".format(repr(bag_of_words)))
print("Dense representation of bag_of_words:\n{}".format(
    bag_of_words.toarray()))

Vocabulary size: 54637
bag_of_words: <8x54637 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>
Dense representation of bag_of_words:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


---
## Discussion

Reflect on your results, and how one might continue to improve them.

## Acknowledgments

For each group member, describe what they did.

## Final meme

Include here a meme describing your experience in this module.